services:
  hello-http:
    build: .
    environment:
      - PORT=3000
      - LATENCY=50
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
    ports:
      - "3000:3000"
